In [21]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt
from sympy import *

In [22]:
def n_degree_taylor(formula, x, x_0, n):
    '''
    Given the analytic expression, x and x_0, calculate
    its nth degree Taylor polynomial
    Note: Variable is defaulted to x
    '''
    var_x = Symbol('x')
    acc = 0
    # Be careful, n+1 because it's up to n
    for i in range(n+1):
        acc += diff(formula, var_x, i).subs(var_x, x_0)/factorial(i)*(x-x_0)**i
    return float(acc)

In [23]:
def n_degree_taylor_derivative(formula, x, x_0, n, n_d):
    '''
    Given the analytic expression, x and x_0, calculate
    its n_d-th derivative based on n-th degree Taylor polynomial
    Note: Variable is defaulted to x
    
    Parameters:
        formula -- analytic expression in sympy
        x -- desired point
        x_0 -- expansion point
        n -- highest degree of polynomial
        n_d -- degree of derivative

    Returns:
        n_d-the derivative based on n-th degree Taylor polynomial
    '''
    var_x = Symbol('x')
    acc = 0
    # Be careful, n+1 because it's up to n
    for i in range(n+1):
        acc += diff(formula, var_x, i).subs(var_x, x_0)/factorial(i)*(var_x-x_0)**i
    derivative = diff(acc, var_x, n_d)
    return float(derivative.subs(var_x, x))

In [24]:
def decimal_to_floating_point(x, n, p):
    """
    Convert a positive decimal number x into its normalized floating-point
    form.
    
    Parameters
    ----------
    x: float
        Input positive decimal number
    n: int
        Number of binary bits in fraction
    p: int
        Exponent range

    Returns
    -------
    f: str
        String of length n representing the fraction part of x in the given floating-point system
    m: int
        Exponent of x in the given floating-point system
    """

    # your implementation goes here

    integer_part = int(x)
    decimal_part = x - integer_part
    int_bin = bin(integer_part)[2:]

    def dec2bin(x):
        x -= int(x)
        bins = []

        while x:
            x *= 2
            bins.append(1 if x>=1. else 0)
            x -= int(x)

        return bins
    decimal_bins = dec2bin(decimal_part)
    if integer_part != 0:
        m = len(str(int_bin)) - 1
        f = str(int_bin)[1:]
        for i in decimal_bins:
            f += str(i)
        if len(f) > n:
            f = f[:n]
        elif len(f) < n:
            f += (n - len(f)) * '0'

    if integer_part == 0:
        m = -(decimal_bins.index(1) + 1)
        f = ''
        for i in range(decimal_bins.index(1) + 1, len(decimal_bins)):
            f += str(decimal_bins[i])
        if len(f) > n:
            f = f[:n]
        elif len(f) < n:
            f += (n - len(f)) * '0'

    return f, m

def bin2dec(x):
    x = str(x)
    a = 0
    for i in range(2, len(x)):
        a += int(x[i]) * 2 ** (-i + 1)
    return a

In [25]:
def hessian(f, X):
    x0, y0 = X[0, 0], X[1,0]
    x, y = Symbol('x'), Symbol('y')
    A = Matrix([f])
    B = Matrix([x, y])
    Hessian = A.jacobian(B).jacobian(B).subs({x:x0, y:y0})
    return np.array(Hessian).astype(np.float64)

def gradient(f, X):
    x0, y0 = X[0, 0], X[1,0]
    x, y = Symbol('x'), Symbol('y')
    A = Matrix([f])
    B = Matrix([x, y])
    Gradient = A.jacobian(B).subs({x:x0, y:y0})
    return np.array(Gradient).astype(np.float64).T

def newtons_method(f, x_init, tol):
    x_new = x_init
    x_prev = np.random.randn(x_init.shape[0])
    cnt = 0
    while(la.norm(gradient(f, x_new)) > tol):
        x_prev = x_new
        print(x_prev)
        s = -la.solve(hessian(f, x_prev), gradient(f, x_prev))
        x_new = x_prev + s
        print(x_new)
        cnt += 1
    return x_new, cnt

In [26]:
# Singular Values for PCA Mean

import numpy.linalg as la

X = np.array([[-1.033, 1.814, 0.933], [-0.072, 1.271, 0.450], [0.730, 0.964, 1.335], [-0.258, 0.738, -1.044]])

X_zeroed = X - X.sum(axis = 0)/X.shape[0]
u, s, vt = la.svd(X_zeroed)
print(X_zeroed)
s


[[-0.87475  0.61725  0.5145 ]
 [ 0.08625  0.07425  0.0315 ]
 [ 0.88825 -0.23275  0.9165 ]
 [-0.09975 -0.45875 -1.4625 ]]


array([1.87479359, 1.39307254, 0.1085284 ])

In [17]:
X = np.array([[0.193, 0.289, -0.624], [-1.775, -1.141, 1.304], [0.137, -0.299, -0.348], [-0.595, -0.706, -0.279]])
X_zeroed = X - X.sum(axis = 0)/X.shape[0]
u, s, vt = la.svd(X_zeroed)
print(X_zeroed)
s

[[ 0.703    0.75325 -0.63725]
 [-1.265   -0.67675  1.29075]
 [ 0.647    0.16525 -0.36125]
 [-0.085   -0.24175 -0.29225]]


array([2.36773931, 0.484151  , 0.28078085])

In [10]:
# NewtonSolve
from sympy import *
x, y = symbols('x y')
X = Matrix([5*x**4 + 6*y**2 - 6, 2*x**3 + 4*y - 5])
x0 = np.array([-1, 0])
Y = Matrix([x, y])
J = X.jacobian(Y)
J_0 = np.array(J.subs({x: x0[0], y: x0[1]})).astype(np.float)
print(J_0)
x1 = x0 - la.inv(J_0) @ np.array(X.subs({x: x0[0], y: x0[1]})).astype(np.float).flatten()
x1

[[-20.   0.]
 [  6.   4.]]


/var/folders/b9/d85h3q6n6x7_fg4hvy45z3v80000gn/T/ipykernel_25950/2709297497.py:8: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  J_0 = np.array(J.subs({x: x0[0], y: x0[1]})).astype(np.float)
/var/folders/b9/d85h3q6n6x7_fg4hvy45z3v80000gn/T/ipykernel_25950/2709297497.py:10: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = x0 - la.inv(J_0)

array([-1.05 ,  1.825])

In [30]:
x, y = symbols('x y')
X = Matrix([4*x**3 + 2*y**2 - 6, 3*x**4 + 5*y - 5])
x0 = np.array([1, -1])
Y = Matrix([x, y])
J = X.jacobian(Y)
J_0 = np.array(J.subs({x: x0[0], y: x0[1]})).astype(np.float)
print(J_0)
x1 = x0 - la.inv(J_0) @ np.array(X.subs({x: x0[0], y: x0[1]})).astype(np.float).flatten()
x1

[[12. -4.]
 [12.  5.]]


array([ 1.25925926, -0.22222222])

In [17]:
# NewtonND-triangular
x, y = symbols('x y')
X = Matrix([x + 4, 6*x**3 + 1*y - 5])
x0 = np.array([1, -1])
Y = Matrix([x, y])
J = X.jacobian(Y)
J_0 = np.array(J.subs({x: x0[0], y: x0[1]})).astype(np.float)
print(J_0)
x1 = x0 - la.inv(J_0) @ np.array(X.subs({x: x0[0], y: x0[1]})).astype(np.float).flatten()
x1

[[ 1.  0.]
 [18.  1.]]


/var/folders/b9/d85h3q6n6x7_fg4hvy45z3v80000gn/T/ipykernel_17460/3007469064.py:7: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  J_0 = np.array(J.subs({x: x0[0], y: x0[1]})).astype(np.float)
/var/folders/b9/d85h3q6n6x7_fg4hvy45z3v80000gn/T/ipykernel_17460/3007469064.py:9: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x1 = x0 - la.inv(J_0) 

array([-4., 89.])

In [ ]:
# Low-rank Approximation
s = np.array([32, 27, 15, 3, 2])
r = 2

d = s[r]
d

15

In [ ]:
# Rounding Error - Decimal to Binary Floating Point
y = 14.375
n = 4
f, m = decimal_to_floating_point(y, n, 100)
print(f, m)
(1 + bin2dec(0.1101)) * 2 **m
abs((1 + bin2dec(0.1101)) * 2 **m - y)

1100 3


0.125

In [24]:
y = 5.6875
n = 4
f, m = decimal_to_floating_point(y, n, 100)
print(f, m)
(1 + bin2dec(0.0111)) * 2 **m

0110 2


5.75

In [17]:
# Floating point: exact representation
n = 3
k = 2 ** (n + 1)
k

16

In [ ]:
# Find the Residual
u3 = np.array([0, 0, 0, 1])
u4 = np.array([0, 0, 1, 0])
b = np.array([9, 12, 5, 2])
np.sqrt((u3 @ b)**2 + (u4 @ b)**2)

5.385164807134504

In [8]:
u3 = np.array([0, 0, 0, 1])
u4 = np.array([0, 0, 1, 0])
b = np.array([5, 12, 6, 3])
np.sqrt((u3 @ b)**2 + (u4 @ b)**2)

6.708203932499369

In [ ]:
# Finding the Eigenvalues of a Matrix
A = np.array([[7, 0],
              [-5, 3]])
lam = np.array([A[0, 0], A[1, 1]])
lamb = 1/(2*lam - 4)
lamb

array([0.1, 0.5])

In [12]:
A = np.array([[7, 0],
              [7, 6]])
lam = np.array([A[0, 0], A[1, 1]])
lamb = 1/(4*lam - 4)
lamb

array([0.04166667, 0.05      ])

In [32]:
# Estimating Errors of Iterative Methods
# Secant method
ek = 0.004898
C = 0.2

r = (1 + 5**0.5)/2
ek1 = ek ** r * C
ek1

3.65933247287981e-05

In [33]:
# Newton's method
ek = 0.05887
C = 0.7

r = 2
ek1 = ek ** r * C
ek1

0.00242597383

In [27]:
# Estimating Errors of Iterative Methods
# Bisection's method
ek = 0.0375
ek_1 = 0.157
C = ek/ek_1**2

r = 2
ek1 = ek ** r * C
ek1


0.0003110680137919997

In [ ]:
# Shifted Inverse Iteration
lamA = np.array([8, -11, -5, 17, 2])
lamB = lamA + 12
lamB

array([20,  1,  7, 29, 14])

In [8]:
lamA = np.array([-5, 8, -14, -17, -11])
lamB = lamA - 7
lamB

array([-12,   1, -21, -24, -18])

In [27]:
# Taylor Series Approximation
n = 3
x0 = 0
x1 = 2
n_degree_taylor(sin(x), x1, x0, n)

0.6666666666666666

In [21]:
n = 3
x0 = 0
x1 = 5
n_degree_taylor(6*x**3+7*x**2+4*x+5, x1, x0, n)

950.0

In [ ]:
# N-Dimension Optimization using Steepest Descent
x, y = symbols('x y')
f = 13*x**2 + 7*x*y + 13*y**2 + 13*sin(y)**2 + 7*cos(x*y)
X0 = np.array([[-3], [3]])
alpha = 0.05
s0 = -gradient(f, X0)
print(s0)
X1 = X0 + alpha*s0
X1

[[ 37.90179174]
 [-72.86249328]]


array([[  4.58035835],
       [-10.57249866]])

In [18]:
x, y = symbols('x y')
f = 8*x**2 + 7*x*y + 8*y**2 + 2*sin(y)**2 + 6*cos(x*y)
X0 = np.array([[-3], [1]])
alpha = 0.2
s0 = -gradient(f, X0)
print(s0)
X1 = X0 + alpha*s0
X1

[[40.15327995]
 [ 5.72156529]]


array([[5.03065599],
       [2.14431306]])

In [ ]:
x, y, z = symbols('x y z')
X = Matrix([16*x**4 + 16*y**4 + z**4 - 16,
            x**2    + y**2    + z**2 - 3,
            x**3    - y])
Y = Matrix([x, y, z])
X.jacobian(Y)

Matrix([
[64*x**3, 64*y**3, 4*z**3],
[    2*x,     2*y,    2*z],
[ 3*x**2,      -1,      0]])

In [ ]:
# Newton's Method
import numpy as np
import numpy.linalg as la

def f(w):
    x, y, z = w
    return np.array([
        16*x**4 + 16*y**4 + z**4 - 16,
        x**2    + y**2    + z**2 - 3,
        x**3    - y])

def J(w):
    x, y, z = w
    return np.array([[64*x**3, 64*y**3, 4*z**3],
                     [2*x, 2*y, 2*z],
                     [3*x**2, -1, 0]])

guesses = np.zeros((5,3))

# Initial guess, don't save this in output
w = np.array([1.,1.,1.])
x = w
for i in range(5):
    x = x - la.inv(J(x)) @ f(x)
    guesses[i] = x

In [ ]:
# Instagram Infinity Loop
import numpy as np
import numpy.linalg as la


M = (A.T / A.sum(axis=1))
x = np.ones(A.shape[0])/A.shape[0]
while not np.array_equal(M @ x, x):
    x = M @ x

prob = x[names.index('Nancy')]

In [ ]:
# Floating Point Summation
sum_p = 0.0
sum_n = 0.0
data = sorted(data,key = abs)
for i in range(len(data)):
    if data[i] > 0:
        sum_p += data[i]
    elif data[i] <= 0:
        sum_n += data[i]
data_sum = sum_p + sum_n

In [ ]:
# Solve rank-deficient system with SVD
import numpy as np

s = S[S!=0]
r = len(s)
# print(U.shape, S.shape, Vh.shape, r, len(b))
U_r = U[:, :r]
Vh_r = Vh[:r, :]
x = Vh_r.T @ (b @ U_r / s)

array([8.114328  , 6.41123866, 5.17721514, 3.8976963 , 3.65027836,
       2.94783879, 2.381553  ])

In [ ]:
# Estimate the amount of clay
import numpy as np

n = 100000
V = 10 * 10 * 2
x = 10 * np.random.rand(n) - 5
y = 10 * np.random.rand(n) - 5
z = 2 * np.random.rand(n)

def check_in(x, y, z):
    if x**2 + y**2 < 25 and z > 0 and z < f(x,y):
        return 1
    return 0

n_in = np.sum(np.array([check_in(x[i], y[i], z[i]) for i in range(n)]))
volume = V * n_in/n

In [ ]:
# Estimate the volume between surfaces
import numpy as np

n = 100000
V = 6 * 6 * 2
x = 6 * np.random.rand(n) - 3
y = 6 * np.random.rand(n) - 3
z = 2 * np.random.rand(n)

def check_in(x, y, z):
    if z > top(x,y) and z < bottom(x,y):
        return 1
    return 0

n_in = np.sum(np.array([check_in(x[i], y[i], z[i]) for i in range(n)]))
volume = V * n_in/n

In [30]:
# Newton Solve 2
x, y = symbols('x y')
x0 = np.array([1,-1])
f = Matrix([4*x**4+5*y**2-6, 6*x**3 + 3*y - 5])
Y = Matrix([x, y])
J = f.jacobian(Y)
J_ = np.array(J.subs({x:x0[0], y:x0[1]})).astype(np.float64)
print(J_)
X_ = np.array(f.subs({x:x0[0], y:x0[1]})).astype(np.float64)
S = la.solve(J_, -X_)
S.flatten()+x0

[[ 16. -10.]
 [ 18.   3.]]


array([ 1.04824561, -0.62280702])

In [11]:
# Inverse Shift iteration
lamb = 0.25
sigma = 6
lama = 1/lamb + sigma
lama

10.0

In [22]:
lamb = 0.2
sigma = 6
lama = 1/lamb + sigma
lama

11.0

In [16]:
# Result of Normalized Power, Inverse, and Shifted Inverse Iteration
lam = np.array([1, 5, 3])
sigma = 2.7
print(1/(lam-sigma))
v = np.array([2, 12, 1]) # according to the result of 1/(lam-sigma)
v/la.norm(v, 1)

[-0.58823529  0.43478261  3.33333333]


array([0.13333333, 0.8       , 0.06666667])

In [12]:
lam = np.array([4, 5, 2])
sigma = 3.9
print(1/(lam-sigma))
v = np.array([4, 6, 11]) # according to the result of 1/(lam-sigma), max abs value index
v/la.norm(v, 1)

[10.          0.90909091 -0.52631579]


array([0.19047619, 0.28571429, 0.52380952])

In [31]:
# Estimating Errors of Iterative Methods
# Bisection
ek = 0.0375
tol = 1e-3
e = ek
cnt = 0
while e > tol:
    e *= 0.5
    cnt += 1
cnt

6

In [6]:
ek = 0.042
tol = 1e-3
e = ek
cnt = 0
while e > tol:
    e *= 0.5
    cnt += 1
cnt

6

In [10]:
# PCA Number of Components
import numpy as np

U = np.array([[-0.1, 0.0, -0.2, -0.3, 0.1, 0.1, 0.0, 0.2, 0.3], [0.4, -0.2, -0.1, 0.1, 0.0, 0.4, 0.3, 0.3, -0.1], [-0.2, -0.2, -0.5, -0.2, 0.0, -0.2, 0.4, -0.2, -0.2], [0.2, 0.3, 0.3, 0.1, 0.2, 0.0, -0.2, 0.0, 0.4], [-0.4, -0.1, 0.3, -0.2, 0.0, 0.1, -0.4, -0.2, -0.4], [0.1, 0.4, -0.1, 0.2, 0.3, -0.3, -0.1, 0.1, -0.4], [0.2, -0.5, 0.0, -0.3, 0.1, -0.1, -0.4, 0.3, 0.1], [0.1, -0.2, 0.5, 0.2, 0.0, -0.4, 0.4, -0.1, -0.1], [0.0, 0.3, 0.2, -0.7, -0.4, 0.0, 0.3, -0.1, -0.1], [-0.5, -0.2, 0.1, 0.1, 0.1, 0.0, 0.2, 0.0, 0.5], [0.1, -0.2, 0.2, 0.2, -0.6, 0.1, 0.0, -0.1, 0.0], [0.0, 0.3, -0.2, 0.2, -0.4, 0.1, -0.2, -0.3, 0.1], [0.0, 0.0, 0.2, -0.1, 0.4, 0.6, 0.2, -0.3, -0.1], [0.4, 0.0, 0.0, -0.3, 0.1, -0.3, 0.0, -0.3, 0.3], [-0.2, 0.3, 0.2, -0.1, -0.2, 0.0, 0.2, 0.6, 0.0]])
S = np.array([[38,  0,  0,  0,  0,  0,  0,  0,  0], [ 0, 29,  0,  0,  0,  0,  0,  0,  0], [ 0,  0, 23,  0,  0,  0,  0,  0,  0], [ 0,  0,  0, 21,  0,  0,  0,  0,  0], [ 0,  0,  0,  0, 17,  0,  0,  0,  0], [ 0,  0,  0,  0,  0, 10,  0,  0,  0], [ 0,  0,  0,  0,  0,  0,  6,  0,  0], [ 0,  0,  0,  0,  0,  0,  0,  4,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  3]])
V = np.array([[-0.1, 0.8, -0.1, 0.0, 0.4, -0.2, -0.2, 0.4, 0.0], [0.1, -0.2, 0.7, 0.2, 0.3, 0.3, -0.5, 0.2, 0.1], [-0.3, 0.0, 0.0, -0.4, 0.4, 0.0, -0.2, -0.6, -0.4], [-0.1, 0.3, 0.4, -0.3, -0.1, 0.0, 0.2, -0.4, 0.7], [-0.7, -0.1, 0.1, -0.4, -0.4, -0.2, -0.1, 0.4, -0.1], [-0.4, -0.4, -0.4, 0.0, 0.5, 0.1, 0.1, 0.1, 0.5], [0.4, -0.3, 0.1, -0.4, 0.1, -0.7, -0.1, 0.1, 0.1], [-0.3, 0.0, 0.0, 0.6, -0.2, -0.5, -0.4, -0.4, 0.1], [0.2, 0.0, -0.4, -0.3, -0.3, 0.3, -0.7, -0.1, 0.2]])

minvalue = 0.78

A_new = U @ S
s = np.diagonal(S)
v = s / np.sum(s)
var = np.array([np.sum(v[:i + 1]) for i in range(len(s))])
(np.argwhere(var > minvalue).reshape(-1))[0]

4

In [11]:
U = np.array([[0.0, 0.1, -0.4, -0.5, 0.2, 0.4, 0.2, -0.1, 0.3, 0.0, 0.4, 0.0, 0.1, 0.3], [0.0, -0.2, 0.3, 0.2, 0.5, 0.2, 0.2, 0.1, -0.3, -0.2, 0.3, -0.5, 0.2,  -0.2], [-0.1, 0.3, -0.3, 0.4, 0.2, 0.4, -0.1, -0.3, -0.2, 0.3, -0.3, 0.1, 0.3,  -0.1], [-0.1, 0.1, 0.2, -0.2, 0.2, -0.2, 0.3, -0.4, -0.1, -0.2, -0.5, -0.2, 0.1,  0.5], [0.0, -0.2, -0.5, 0.1, -0.1, -0.4, 0.1, -0.4, 0.1, -0.2, 0.0, -0.3, -0.1,  -0.3], [-0.1, 0.5, 0.0, -0.3, -0.2, -0.2, 0.0, 0.1, -0.5, 0.4, 0.2, -0.4, -0.2,  -0.1], [0.3, 0.1, -0.1, -0.2, 0.3, -0.3, -0.3, 0.1, -0.2, -0.1, 0.2, 0.4, 0.4,  -0.1], [-0.2, 0.2, 0.3, -0.1, -0.1, 0.1, -0.3, -0.6, 0.0, -0.4, 0.3, 0.1, -0.1,  -0.1], [0.1, 0.1, -0.2, 0.4, -0.3, -0.2, 0.2, 0.1, -0.3, -0.3, 0.3, 0.0, 0.2,  0.4], [-0.5, 0.0, -0.3, 0.0, 0.3, 0.0, 0.1, 0.2, -0.3, -0.3, 0.0, 0.3, -0.5,  0.1], [0.1, 0.0, -0.1, 0.2, 0.3, -0.2, -0.6, 0.0, 0.2, 0.1, 0.1, -0.4, -0.2,  0.4], [0.1, 0.0, -0.3, -0.4, 0.0, 0.1, -0.3, 0.2, -0.2, -0.5, -0.4, -0.2, 0.1,  -0.3], [0.3, -0.6, 0.0, -0.1, -0.1, 0.1, -0.1, -0.4, -0.5, 0.2, 0.0, 0.1, -0.2,  0.1], [-0.5, -0.3, 0.0, -0.1, -0.4, 0.2, -0.3, 0.2, -0.1, 0.0, 0.1, -0.1, 0.3,  0.3], [0.5, 0.3, 0.0, 0.1, -0.1, 0.4, 0.0, 0.1, 0.0, -0.2, -0.1, -0.1, -0.3,  0.2]])
S = np.array([[36,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], [ 0, 31,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], [ 0,  0, 29,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], [ 0,  0,  0, 24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0], [ 0,  0,  0,  0, 23,  0,  0,  0,  0,  0,  0,  0,  0,  0], [ 0,  0,  0,  0,  0, 22,  0,  0,  0,  0,  0,  0,  0,  0], [ 0,  0,  0,  0,  0,  0, 21,  0,  0,  0,  0,  0,  0,  0], [ 0,  0,  0,  0,  0,  0,  0, 17,  0,  0,  0,  0,  0,  0], [ 0,  0,  0,  0,  0,  0,  0,  0, 16,  0,  0,  0,  0,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  0], [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  2]])
V = np.array([[-0.3, -0.3, 0.3, 0.1, -0.1, 0.3, -0.3, -0.3, -0.1, 0.0, -0.2, -0.4, 0.1,  -0.5], [0.4, -0.1, -0.2, -0.3, 0.3, 0.2, 0.0, -0.1, -0.4, 0.0, -0.1, -0.1, 0.6,  0.0], [0.1, -0.4, -0.4, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, -0.5, 0.0, -0.4, -0.2,  0.2], [-0.1, -0.3, 0.3, -0.1, 0.5, 0.1, 0.1, 0.1, -0.2, 0.4, 0.2, -0.1, -0.3,  0.3], [0.2, -0.1, 0.1, 0.0, -0.5, 0.0, 0.1, 0.0, -0.2, 0.1, 0.6, -0.4, 0.2,  0.1], [0.1, -0.7, 0.0, -0.3, -0.3, -0.3, 0.0, -0.1, 0.1, 0.0, -0.1, 0.5, 0.0,  0.1], [0.4, 0.0, 0.0, 0.2, -0.1, 0.5, -0.4, -0.3, -0.2, 0.0, 0.0, 0.3, -0.4,  0.2], [0.2, 0.2, 0.5, -0.3, 0.0, -0.1, 0.2, -0.5, 0.2, -0.2, -0.2, -0.2, 0.0,  0.3], [0.1, 0.1, 0.1, -0.6, -0.3, 0.1, -0.1, 0.5, -0.2, -0.2, -0.1, -0.1, -0.3,  -0.1], [0.2, -0.1, 0.5, 0.2, 0.2, 0.1, -0.2, 0.4, 0.2, -0.4, 0.2, 0.2, 0.4, 0.0], [0.4, -0.1, 0.2, 0.3, -0.2, 0.0, 0.4, 0.3, -0.1, 0.3, -0.5, -0.1, 0.0,  0.0], [0.2, 0.0, 0.1, 0.3, 0.2, -0.6, -0.3, -0.1, -0.4, -0.3, 0.1, -0.1, -0.3,  -0.2], [-0.4, 0.0, 0.1, 0.1, -0.1, 0.2, 0.5, 0.0, -0.5, -0.4, 0.0, 0.2, 0.0,  0.1], [-0.3, 0.0, -0.1, 0.1, -0.2, -0.2, -0.5, 0.1, -0.2, 0.0, -0.3, -0.2, 0.2,  0.6]])

minvalue = 0.54

A_new = U @ S
s = np.diagonal(S)
v = s / np.sum(s)
var = np.array([np.sum(v[:i + 1]) for i in range(len(s))])
(np.argwhere(var > minvalue).reshape(-1))[0]

4

In [29]:
# Optimization ND NewtonMethod one step
x, y = symbols('x y')
x0 = np.array([[3], [2]])
f = 5 * x**4 + 4 * y**2
H = hessian(f, x0)
s = -la.solve(H, gradient(f, x0))
print('Hessian: %s' %H)
print('Step: %s'%s)
x1 = x0 + s
print('x1: %s' %x1)

Hessian: [[540.   0.]
 [  0.   8.]]
Step: [[-1.]
 [-2.]]
x1: [[2.]
 [0.]]


In [19]:
x, y = symbols('x y')
x0 = np.array([[2], [1]])
f = 2 * x**3 + 3 * y**4
H = hessian(f, x0)
s = -la.solve(H, gradient(f, x0))
print('Hessian: %s' %H)
print('Step: %s'%s)
x1 = x0 + s
print('x1: %s' %x1)

Hessian: [[24.  0.]
 [ 0. 36.]]
Step: [[-1.        ]
 [-0.33333333]]
x1: [[1.        ]
 [0.66666667]]


In [29]:
# Finite Difference: Calculation R -> R
x = Symbol('x')
y = -log(x)
x0 = 0.1
h = 0.01
(y.subs(x, x0+h) - y.subs(x, x0-h))/2/h
# 看情况
x = Symbol('x')
y = exp(x)
x0 = 0.3
h = 0.06
y0 = 1.349859
(y0 - y.subs(x, x0-h))/h

1.31016416130992

In [18]:
x = Symbol('x')
y = exp(x)
x0 = 0.7
h = 0.07
(y.subs(x, x0+h) - y.subs(x, x0-h))/2/h

2.01539767514694

In [46]:
x = Symbol('x')
y = -log(x)
x0 = 0.1
h = 0.01
(y.subs(x, x0+h) - y.subs(x, x0-h))/2/h
# 看情况
x = Symbol('x')
y = -log(x)
x0 = 0.7
h = 0.05
y0 = 0.356675
(y0 - y.subs(x, x0-h))/h

-1.48215832184909

In [7]:
# Summing Two Floating-Point Numbers
def sum_minifloats(x,y):
    # compute sum z = x + y
    # return z as a float
    z = decoding(x) + decoding(y)
    return z

def decoding(x):
    a = (-1)**x[0]
    E = np.array([x[i]*2**(5-i) for i in range(1,6)]).sum().astype(np.int) - 16
    print(E)
    M = np.array([x[i]*2**(5-i) for i in range(6,10)]).sum()
    print(M, a)
    return a*(1+M)*2.**E
decoding(x)

-3
0.8125 -1


-0.2265625

In [27]:
# Properties of a Floating Point System
n = 6
m = (-8, 9)
# smallest positive normalized number
2**m[0]

0.00390625

In [10]:
n = 6
m = (-7, 8)
# largest value of K that [-k, k] are exactly represenable
2**(n+1)

128

In [26]:
n = 5
m = (-7, 8)
# Largest normalized number
(1+bin2dec('0.' + n*'1'))*2**m[1]

504.0

In [7]:
n = 4
m = (-8, 9)
# smallest positive subnormal number
(bin2dec('0.' + (n-1)*'0'+ '1'))*2**m[0]

0.000244140625

In [15]:
n = 7
m = (-126, 127)
# Machine epsilon
2 ** -n

0.0078125

In [16]:
# Taylor: Shifting the Expansion Point
x = Symbol('x')
f = 2 - 9*x + x**2
x0 = 3
order = 2
for i in range(order):
    print(diff(f, x, i+1).subs(x, x0)/factorial(i+1))

-3
1


In [8]:
x = Symbol('x')
f = 6 - 6*x + 5*x**2
x0 = 3
order = 2
for i in range(order):
    print(diff(f, x, i+1).subs(x, x0)/factorial(i+1))

24
5


In [ ]:
# Finite Difference
import numpy as np

def f(x):
    return x[0]**4 + x[1]*x[6] + x[2]**2 + x[3]**3 + x[4]*x[5] + x[5]**3 + x[6]**3

n = len(xvec)
approx_gradient = np.zeros(n)
h = 0.9
for i in range(n):
    pert = np.zeros(n)
    pert[i] = h
    approx_gradient[i] = (f(xvec) - f(xvec-pert))/h

In [ ]:
# Grubhub Coupon
import numpy as np
import numpy.linalg as la

A = np.array([[0, 0, 1, 0, 0],
              [1, 0, 0, 0, 0],
              [1, 1, 0, 1, 1],
              [0, 0, 1, 0, 0],
              [1, 1, 1, 0, 0]])
C = (A / A.sum(axis=0))
x = np.ones(A.shape[0])/A.shape[0]

for i in range(10000):
    x = C @ x

p = x[restaurants.index('Mexican')]

In [ ]:
# SVD Compression V2
import numpy as np
import matplotlib.pyplot as plt
import numpy.linalg as la

u, s, vt = la.svd(image, full_matrices = False)
print(u.shape, s.shape, vt.shape)
k = 0
image_compressed = 0
for i in range(len(s)):
    image_compressed += s[i] * np.outer(u[:,i], vt[i])
    k+=1
    if la.norm(image_compressed - image, 2) <= eps:
        break
plt.figure()
plt.imshow(image, cmap="gray")
plt.title("Original Image")

plt.figure()
plt.imshow(image_compressed, cmap="gray")
plt.title("Compressed: $eps$ = {}".format(eps) + ",  $k$ = {}".format(k))

Newton Concept
<img src = '../Quiz/Quiz5/15.jpg'>

In [30]:
# NewtonSolve
x, y = symbols('x y')
f = Matrix([4*x**2 + 6*y**3 - 6, 3*x**4 + 5*y -5])
X0 = np.array([-1, 1])

Y = Matrix([x, y])
J = (f.jacobian(Y))

J_ = np.array(J.subs({x:X0[0], y:X0[1]})).astype(np.float64)
print(J_)
f_ = np.array(f.subs({x:X0[0], y:X0[1]})).astype(np.float64)

S = la.solve(J_, -f_)
S.flatten()+X0

[[ -8.  18.]
 [-12.   5.]]


array([-0.80681818,  0.86363636])

In [38]:
# Taylor Series approximation
x = Symbol('x')
f_x0 = [3, -2, 9, -3, 7]
x0 = 0
xp = 4

f = 0
for i in range(len(f_x0)):
    f += f_x0[i]/factorial(i)*(x - x0)**i
float(f.subs(x,xp))

109.66666666666667

In [17]:
x = Symbol('x')
f_x0 = [3, -5, 3, -2, 4]
x0 = 0
xp = 4

f = 0
for i in range(len(f_x0)):
    f += f_x0[i]/factorial(i)*(x - x0)**i
float(f.subs(x,xp))

28.333333333333332

In [40]:
# Eigenvalues of Matrix Polynomials
lam = -2
lamb = lam**3 - 3*lam**2 - 8*lam + 12
lamb

8

In [20]:
lam = 3
lamb = lam**3 - 4*lam**2 -9*lam + 13
lamb

-23

In [43]:
# Floating point machine epsilon
n = 2
m = (-85, 84)
2**(-n)

0.25

In [27]:
# Taylor Series Approximation Derivative
x = symbols('x')
n_degree_taylor_derivative(np.e**x,3,0,2,1)

4.0

In [34]:
x = symbols('x')
n_degree_taylor_derivative(cos(x),3,0,2,1)

-3.0

: 

In [28]:
# Matrix Condition Number Approximation
x1 = 1
x2 = 2 
x3 = 4
Ax1 = 30
Ax2 = 20
Ax3 = 80

X = np.array([x1, x2, x3])
AX = np.array([Ax1, Ax2, Ax3])
A = AX/X
np.max(A) / np.min(A)

3.0

In [16]:
# Error prediction
C = 0.5
e0 = 0.5
iteration = 4

e = e0
for i in range(iteration):
    e *= C
e

0.03125

In [31]:
# Finite Difference Gradient
x, y, z = symbols('x y z')
X0 = np.array([1, 1, 1])
phi = Matrix([x*y + x + z])
h = 0.1

# Forward

phi0 = np.array(phi.subs({x:X0[0], y:X0[1], z:X0[2]})).astype(np.float64)
for i in range(3):
    a = np.zeros(3)
    a[i] = h
    X = X0 + a
    phix = np.array(phi.subs({x:X[0], y:X[1], z:X[2]})).astype(np.float64)
    print((phi0-phix)/h)

# Backward

# for i in range(3):
#     a = np.zeros(3)
#     a[i] = h
#     X = X0 - a
#     phix = np.array(phi.subs({x:X[0], y:X[1], z:X[2]})).astype(np.float64)
#     print(-(phi0-phix)/h)

[[-2.]]
[[-1.]]
[[-1.]]


In [12]:
x, y, z = symbols('x y z')
X0 = np.array([1, 1, 1])
v = Matrix([2*x*y + z**2])
h = 0.1

v0 = np.array(v.subs({x:X0[0], y:X0[1], z:X0[2]})).astype(np.float64)
for i in range(3):
    a = np.zeros(3)
    a[i] = h
    X = X0 + a
    vx = np.array(v.subs({x:X[0], y:X[1], z:X[2]})).astype(np.float64)
    print((-v0+vx)/h)

[[2.]]
[[2.]]
[[2.1]]


In [32]:
# Least-Squares Minimum Norm Solution
U = np.array([[0, 0, 0, 0],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 1],
              [1, 0, 0, 0]])
Sigma = np.array([[9, 0, 0, 0],
                  [0, 5, 0, 0],
                  [0, 0, 4, 0],
                  [0, 0, 0, 0]])
VT = np.array([[0.00, -0.97, 0.24, 0.00],
               [0.00, -0.24, -0.97, 0],
               [0.66, 0.00, 0.00, 0.75],
               [-0.75, 0.00, 0, 0.66]])
b = np.array([7, 0, 8, 7, 4])

Sigma_p = 1 / Sigma.T
Sigma_p[Sigma_p == np.inf] = 0
x = VT.T @ Sigma_p @ U.T @ b
x

<ipython-input-32-ae80513166ea>:17: RuntimeWarning: divide by zero encountered in true_divide
  Sigma_p = 1 / Sigma.T


array([ 1.32      , -0.43111111,  0.10666667,  1.5       ])

In [6]:
# Floating Point Precision
decimal_to_floating_point(153.25, 100, 100)

('0011001010000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
 7)

In [7]:
# Find Normalized Eigenvector G
v = np.array([11,16,12])
v/la.norm(v, 1)

array([0.28205128, 0.41025641, 0.30769231])

In [10]:
# Relative Error in Floating Point
decimal_to_floating_point(8.5, 2, 100)
(8.5-8)/8.5

0.058823529411764705

In [28]:
# Similarity Transformation of a Matrix
A = np.array([[7, -1],
              [0, 6]])
D = np.diag(la.eig(A)[0])

X0 = la.eig(A)[1]
X = np.zeros_like(X0)
for i in range(D.shape[0]):
    X[:,i] = X0[:, i]/la.norm(X0[:, i], np.inf)

print(X)
print(D)

[[1. 1.]
 [0. 1.]]
[[7. 0.]
 [0. 6.]]


In [24]:
#2.84375
#10.1100011

(2.84375-2.75)*2*2*2

0.75

In [1]:
14+11+16

41

In [4]:
16/41

0.3902439024390244

In [5]:
import numpy as np
len(np.unique([11.5,10.0,6.0,9.5,10.0,8.0,6.5,9.5,11.0,9.5,5.5]))

8

In [ ]:
#1.171875

#1.001011

In [15]:
2**(-3)+2**(-5)+2**(-6)


0.171875

In [17]:
2**(-3)+2**(-4)-0.171875

0.015625

In [18]:
2**(-6)

0.015625

In [19]:
(10**2+9**2)**0.5

13.45362404707371

In [ ]:
# 168.125

In [ ]:
10101000.001

In [30]:
2**(3)+2**(5)+2**(7)

168

In [34]:
A = np.array([1,2,3,4,5])
B = np.argmin(A)
B

0

In [35]:
colors = ['red', 'yellow', 'blue', 'purple']

In [38]:
1-0.02-0.1-0.15

0.73

In [100]:
import numpy as np

A = np.array([60.0,72.0,30.0,58.0])

M = np.array([
    [0.74,0.02,0.00,0.02],
    [0.03,0.58,0.10,0.10],
    [0.12,0.20,0.60,0.15],
    [0.11,0.20,0.30,0.73]
    ])
    
threshold = 55.00/4
    
for i in range(1,100):
    
    A = M@A
    print(A[0])
    
    if (A[0]<=threshold):
        seconds = 10*i
        bulbs = A
        break
    

46.99999999999999
37.273999999999994
30.118419999999997
24.900297
21.112615098
18.36970292954
16.385611396705002
14.951103061869947
13.914105570364907
13.164466202478273


In [94]:
A

array([ 13.1644662 ,  40.26523025,  62.79468269, 103.77562086])

In [98]:
bulbs

array([47.  , 52.36, 48.3 , 72.34])

In [110]:
A[np.random.randint(0,4,3)]

array([103.77562086, 103.77562086,  62.79468269])

In [112]:
import numpy as np

def losing_dice(dice_list):
    
    lose_probs = []
    for dice in dice_list:
        num_iter = 10000
        num_lose = 0
        for i in range(num_iter):
            choice = dice[np.random.randint(0,len(dice),3)]
            if choice[0]<choice[1] and choice[1]<choice[2]:
                continue
            elif choice[0]>choice[1] and choice[1]>choice[2]:
                continue
            else:
                num_lose +=1
        lose_probs.append(num_lose/num_iter)
    
    lose_probs = np.array(lose_probs)
    # insert your code here
    selected_die = dice[np.argmax(lose_probs)]
    lose_prob  = max(lose_probs)

    return selected_die, lose_prob

In [111]:
dice_list = [
      [1, 2, 3, 4, 5, 6],
      [1, 1, 3, 5, 5],
      [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    ]

In [117]:
     choice = dice_list[0][np.random.randint(0,len(dice_list[0]),3)]

TypeError: only integer scalar arrays can be converted to a scalar index

In [126]:
A = np.random.randint(0,9,1)

In [122]:
dice_list = [1, 2, 3, 4, 5, 6]

In [127]:
dice_list(A)

TypeError: 'list' object is not callable